/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as LayoutTicketsIndexRouteImport } from './routes/_layout/tickets/index'
import { Route as LayoutTicketsNewRouteImport } from './routes/_layout/tickets/new'
import { Route as LayoutTicketsIdRouteImport } from './routes/_layout/tickets/$id'
import { Route as LayoutProfileSettingsRouteImport } from './routes/_layout/profile/settings'
import { Route as LayoutProfileSessionsRouteImport } from './routes/_layout/profile/sessions'
import { Route as LayoutHistoriesNotificationsRouteImport } from './routes/_layout/histories/notifications'
import { Route as LayoutHistoriesActivitiesRouteImport } from './routes/_layout/histories/activities'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminTrashRouteImport } from './routes/_layout/admin/trash'
import { Route as LayoutAdminStatusesRouteImport } from './routes/_layout/admin/statuses'
import { Route as LayoutAdminServicesRouteImport } from './routes/_layout/admin/services'
import { Route as LayoutAdminRolesRouteImport } from './routes/_layout/admin/roles'
import { Route as LayoutAdminPrioritiesRouteImport } from './routes/_layout/admin/priorities'
import { Route as LayoutAdminLogsRouteImport } from './routes/_layout/admin/logs'
import { Route as LayoutAdminCategoriesRouteImport } from './routes/_layout/admin/categories'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutTicketsIndexRoute = LayoutTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketsNewRoute = LayoutTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketsIdRoute = LayoutTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileSettingsRoute = LayoutProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileSessionsRoute = LayoutProfileSessionsRouteImport.update({
  id: '/profile/sessions',
  path: '/profile/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoriesNotificationsRoute =
  LayoutHistoriesNotificationsRouteImport.update({
    id: '/histories/notifications',
    path: '/histories/notifications',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHistoriesActivitiesRoute =
  LayoutHistoriesActivitiesRouteImport.update({
    id: '/histories/activities',
    path: '/histories/activities',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminTrashRoute = LayoutAdminTrashRouteImport.update({
  id: '/admin/trash',
  path: '/admin/trash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminStatusesRoute = LayoutAdminStatusesRouteImport.update({
  id: '/admin/statuses',
  path: '/admin/statuses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminServicesRoute = LayoutAdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRolesRoute = LayoutAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminPrioritiesRoute = LayoutAdminPrioritiesRouteImport.update({
  id: '/admin/priorities',
  path: '/admin/priorities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminLogsRoute = LayoutAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminCategoriesRoute = LayoutAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/': typeof LayoutIndexRoute
  '/admin/categories': typeof LayoutAdminCategoriesRoute
  '/admin/logs': typeof LayoutAdminLogsRoute
  '/admin/priorities': typeof LayoutAdminPrioritiesRoute
  '/admin/roles': typeof LayoutAdminRolesRoute
  '/admin/services': typeof LayoutAdminServicesRoute
  '/admin/statuses': typeof LayoutAdminStatusesRoute
  '/admin/trash': typeof LayoutAdminTrashRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/histories/activities': typeof LayoutHistoriesActivitiesRoute
  '/histories/notifications': typeof LayoutHistoriesNotificationsRoute
  '/profile/sessions': typeof LayoutProfileSessionsRoute
  '/profile/settings': typeof LayoutProfileSettingsRoute
  '/tickets/$id': typeof LayoutTicketsIdRoute
  '/tickets/new': typeof LayoutTicketsNewRoute
  '/tickets': typeof LayoutTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/': typeof LayoutIndexRoute
  '/admin/categories': typeof LayoutAdminCategoriesRoute
  '/admin/logs': typeof LayoutAdminLogsRoute
  '/admin/priorities': typeof LayoutAdminPrioritiesRoute
  '/admin/roles': typeof LayoutAdminRolesRoute
  '/admin/services': typeof LayoutAdminServicesRoute
  '/admin/statuses': typeof LayoutAdminStatusesRoute
  '/admin/trash': typeof LayoutAdminTrashRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/histories/activities': typeof LayoutHistoriesActivitiesRoute
  '/histories/notifications': typeof LayoutHistoriesNotificationsRoute
  '/profile/sessions': typeof LayoutProfileSessionsRoute
  '/profile/settings': typeof LayoutProfileSettingsRoute
  '/tickets/$id': typeof LayoutTicketsIdRoute
  '/tickets/new': typeof LayoutTicketsNewRoute
  '/tickets': typeof LayoutTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/categories': typeof LayoutAdminCategoriesRoute
  '/_layout/admin/logs': typeof LayoutAdminLogsRoute
  '/_layout/admin/priorities': typeof LayoutAdminPrioritiesRoute
  '/_layout/admin/roles': typeof LayoutAdminRolesRoute
  '/_layout/admin/services': typeof LayoutAdminServicesRoute
  '/_layout/admin/statuses': typeof LayoutAdminStatusesRoute
  '/_layout/admin/trash': typeof LayoutAdminTrashRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/histories/activities': typeof LayoutHistoriesActivitiesRoute
  '/_layout/histories/notifications': typeof LayoutHistoriesNotificationsRoute
  '/_layout/profile/sessions': typeof LayoutProfileSessionsRoute
  '/_layout/profile/settings': typeof LayoutProfileSettingsRoute
  '/_layout/tickets/$id': typeof LayoutTicketsIdRoute
  '/_layout/tickets/new': typeof LayoutTicketsNewRoute
  '/_layout/tickets/': typeof LayoutTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/dashboard'
    | '/'
    | '/admin/categories'
    | '/admin/logs'
    | '/admin/priorities'
    | '/admin/roles'
    | '/admin/services'
    | '/admin/statuses'
    | '/admin/trash'
    | '/admin/users'
    | '/histories/activities'
    | '/histories/notifications'
    | '/profile/sessions'
    | '/profile/settings'
    | '/tickets/$id'
    | '/tickets/new'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/dashboard'
    | '/'
    | '/admin/categories'
    | '/admin/logs'
    | '/admin/priorities'
    | '/admin/roles'
    | '/admin/services'
    | '/admin/statuses'
    | '/admin/trash'
    | '/admin/users'
    | '/histories/activities'
    | '/histories/notifications'
    | '/profile/sessions'
    | '/profile/settings'
    | '/tickets/$id'
    | '/tickets/new'
    | '/tickets'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/_auth/login'
    | '/_auth/register'
    | '/_layout/dashboard'
    | '/_layout/'
    | '/_layout/admin/categories'
    | '/_layout/admin/logs'
    | '/_layout/admin/priorities'
    | '/_layout/admin/roles'
    | '/_layout/admin/services'
    | '/_layout/admin/statuses'
    | '/_layout/admin/trash'
    | '/_layout/admin/users'
    | '/_layout/histories/activities'
    | '/_layout/histories/notifications'
    | '/_layout/profile/sessions'
    | '/_layout/profile/settings'
    | '/_layout/tickets/$id'
    | '/_layout/tickets/new'
    | '/_layout/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/tickets/': {
      id: '/_layout/tickets/'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof LayoutTicketsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tickets/new': {
      id: '/_layout/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof LayoutTicketsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tickets/$id': {
      id: '/_layout/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof LayoutTicketsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/settings': {
      id: '/_layout/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof LayoutProfileSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/sessions': {
      id: '/_layout/profile/sessions'
      path: '/profile/sessions'
      fullPath: '/profile/sessions'
      preLoaderRoute: typeof LayoutProfileSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/histories/notifications': {
      id: '/_layout/histories/notifications'
      path: '/histories/notifications'
      fullPath: '/histories/notifications'
      preLoaderRoute: typeof LayoutHistoriesNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/histories/activities': {
      id: '/_layout/histories/activities'
      path: '/histories/activities'
      fullPath: '/histories/activities'
      preLoaderRoute: typeof LayoutHistoriesActivitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/trash': {
      id: '/_layout/admin/trash'
      path: '/admin/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof LayoutAdminTrashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/statuses': {
      id: '/_layout/admin/statuses'
      path: '/admin/statuses'
      fullPath: '/admin/statuses'
      preLoaderRoute: typeof LayoutAdminStatusesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/services': {
      id: '/_layout/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof LayoutAdminServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/roles': {
      id: '/_layout/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof LayoutAdminRolesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/priorities': {
      id: '/_layout/admin/priorities'
      path: '/admin/priorities'
      fullPath: '/admin/priorities'
      preLoaderRoute: typeof LayoutAdminPrioritiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/logs': {
      id: '/_layout/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof LayoutAdminLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/categories': {
      id: '/_layout/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof LayoutAdminCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminCategoriesRoute: typeof LayoutAdminCategoriesRoute
  LayoutAdminLogsRoute: typeof LayoutAdminLogsRoute
  LayoutAdminPrioritiesRoute: typeof LayoutAdminPrioritiesRoute
  LayoutAdminRolesRoute: typeof LayoutAdminRolesRoute
  LayoutAdminServicesRoute: typeof LayoutAdminServicesRoute
  LayoutAdminStatusesRoute: typeof LayoutAdminStatusesRoute
  LayoutAdminTrashRoute: typeof LayoutAdminTrashRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutHistoriesActivitiesRoute: typeof LayoutHistoriesActivitiesRoute
  LayoutHistoriesNotificationsRoute: typeof LayoutHistoriesNotificationsRoute
  LayoutProfileSessionsRoute: typeof LayoutProfileSessionsRoute
  LayoutProfileSettingsRoute: typeof LayoutProfileSettingsRoute
  LayoutTicketsIdRoute: typeof LayoutTicketsIdRoute
  LayoutTicketsNewRoute: typeof LayoutTicketsNewRoute
  LayoutTicketsIndexRoute: typeof LayoutTicketsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminCategoriesRoute: LayoutAdminCategoriesRoute,
  LayoutAdminLogsRoute: LayoutAdminLogsRoute,
  LayoutAdminPrioritiesRoute: LayoutAdminPrioritiesRoute,
  LayoutAdminRolesRoute: LayoutAdminRolesRoute,
  LayoutAdminServicesRoute: LayoutAdminServicesRoute,
  LayoutAdminStatusesRoute: LayoutAdminStatusesRoute,
  LayoutAdminTrashRoute: LayoutAdminTrashRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutHistoriesActivitiesRoute: LayoutHistoriesActivitiesRoute,
  LayoutHistoriesNotificationsRoute: LayoutHistoriesNotificationsRoute,
  LayoutProfileSessionsRoute: LayoutProfileSessionsRoute,
  LayoutProfileSettingsRoute: LayoutProfileSettingsRoute,
  LayoutTicketsIdRoute: LayoutTicketsIdRoute,
  LayoutTicketsNewRoute: LayoutTicketsNewRoute,
  LayoutTicketsIndexRoute: LayoutTicketsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
